name: Docker Publish

#on:
#  push:
#    branches: [ main ]
#    tags:
#      - '*'

on:
  pull_request:
    branches: [ main ]

jobs:
  docker_publish:
    # run workflow only on numaproj/numaflow-python repository
    if: ${{ github.repository }} == "numaproj/numaflow-python"
    name: Build, Tag, and Push Image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # TODO: rewrite asyncio_reduce example using latest SDK version, as it is currently using old methods
        # then add to example_directories matrix
        example_directories: [
          "examples/map/even_odd"
        ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          pip install poetry
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Quay.io registry
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.NUMAIO_USERNAME }}
          password: ${{ secrets.NUMAIO_PASSWORD }}
      - name: Build, tag, and push images
        run: |
          ./hack/update_examples.sh --build-push-example ${{ matrix.example_directories }}
